import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Grill SendWish Stock Management.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full md:max-w-7xl mx-auto pt-6 px-4 md:px-6">
          <div>
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
